# Generated by Django 5.2.6 on 2025-09-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brainitem",
            name="all_specs",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="brainitem",
            name="discount_price",
            field=models.IntegerField(blank=True),
        ),
    ]
