# Generated by Django 5.2.6 on 2025-09-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_app", "0002_alter_brainitem_all_specs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brainitem",
            name="discount_price",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
