# Generated by Django 5.2.6 on 2025-09-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_app", "0003_alter_brainitem_discount_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brainitem",
            name="all_specs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="brainitem",
            name="discount_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="brainitem",
            name="review_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
