# Generated by Django 5.2.6 on 2025-10-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrainItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=256)),
                ("color", models.CharField(max_length=25)),
                ("storage", models.CharField(max_length=20)),
                ("seller", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("discount_price", models.IntegerField(blank=True, null=True)),
                ("photos", models.TextField()),
                ("item_id", models.CharField(max_length=25)),
                ("review_count", models.IntegerField(blank=True, null=True)),
                ("series", models.CharField(max_length=256)),
                ("screen", models.CharField(max_length=10)),
                ("resolution", models.CharField(max_length=15)),
                ("all_specs", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
